### ISSUE TITLE
Do not install ceph-common on "Admin" nodes

### ISSUE THREAD

**Issue by ricardoasmarques** [ceph/ceph-salt#120]
Instead of installing `ceph-common` in "Admin" nodes, `ceph-salt` should simply create a `ceph='cephadm shell -- ceph'` alias (e.g. /etc/profile.d/ceph.sh)

**Depends on https://github.com/ceph/ceph/pull/33829**

**Comment by ricardoasmarques** [comment]
Maybe we can do the same for crushtool: `cephadm shell -- crushtool --help`

**Comment by smithfarm** [comment]
As Denis Polom reported in Rocket.Chat, this approach is not robust, because if the command line references a file or path that is on the host, but not in the container, the command will fail.

For example:

```
# cephadm shell -- crushtool -d file.bin -o file.txt
INFO:cephadm:Using recent ceph image registry.suse.de/suse/sle-15-sp2/update/products/ses7/milestones/containers/ses/7/ceph/ceph:latest
crushtool: error reading 'file.bin': can't open file.bin: (2) No such file or directory
```

This could be surprising if:

* the file is present on the host and
* the user issues the crushtool on the host but it gets converted into `cephadm shell -- crushtool $@` by an alias added (more or less silently) by ceph-salt to `/etc/bash.d`

**Comment by ricardoasmarques** [comment]
Good point, I think this is a valid argument to not create an alias, and force the user to type `cephadm shell` explicitly.

**Comment by ricardoasmarques** [comment]
Using `cephadm shell -- ceph` instead of `ceph` has usability issues especially when referencing files via `--mount` option.

For this reason, we will continue installing `ceph-common` for now.
