### ISSUE TITLE
Add service spec option under '/cephadm_bootstrap'

### ISSUE THREAD

**Issue by ricardoasmarques** [ceph/ceph-salt#215]
Since https://github.com/ceph/ceph/pull/34879/, `cephadm bootstrap` has a new `--apply-spec` option that can be used to provide initial service spec.

**Comment by smithfarm** [comment]
As of #308 we are using the `--apply-spec` option to ensure that `cephadm bootstrap` only creates a single MON and a single MGR (both on the bootstrap node). Otherwise, it will create up to 5 MONs and 2 MGRs (on random nodes).

As a result, assuming #308 gets merged, this option will not be available for users.

Also, to put it bluntly, if we give users a way to send their own handwritten service spec to `cephadm bootstrap`, ceph-salt will be blamed when it leads to an unexpected result.

So I would vote to not add this "service spec" feature to ceph-salt.

**Comment by ricardoasmarques** [comment]
@smithfarm Agree, "service spec" must be provided via `cephadm` directly, not via `ceph-salt`.

**Comment by sebastian-philipp** [comment]
> Also, to put it bluntly, if we give users a way to send their own handwritten service spec to cephadm bootstrap, ceph-salt will be blamed when it leads to an unexpected result.

That sounds a bit strange as an explanation. 

Still. +1 for closing this here.
