### ISSUE TITLE
Need to be able to have the master node *not* managed by cephadm

### ISSUE THREAD

**Issue by tserong** [ceph/ceph-salt#217]
I believe that in most cases it's inadvisable to have the master node also run ceph daemons, because that would make one of your cluster nodes also the salt-master, which suddenly makes that node "special" and different somehow. This is probably especially true where the salt-master node is also running SUMA or other management tooling that's well outside Ceph's domain.

Right now however, all nodes are added to cephadm's control, so when you deploy some more mons or mgrs after initial bootstrap, some may end up running on the master node. I think we need a way to disable this, i.e. keep the master in the list of minions (so it can be set as the time server), but skip the `ceph orch host add` step for the master node.

**Comment by ricardoasmarques** [comment]
Since https://github.com/ceph/ceph-salt/pull/206, `/time_server/server_hostname` can be set to a host/minion not managed by `ceph-salt` (a minion that is not in `/ceph_cluster/minions`).

This assumes that we already have a time server that was previously configured (manually or with any other tool).

If we what `ceph-salt` to be able to set-up/manage a time server that is not a ceph host, I think we will need a new `cephadm` role, and `ceph-salt` should do [1] only on nodes with `cephadm` role.

My main concern with this approach is the usability part, because we will need to run one more command to add a ceph node (maybe it's not a problem):

```
ceph-salt config /ceph_cluster/minions add <new_ceph_node>
ceph-salt config /ceph_cluster/roles/cephadm add <new_ceph_node>
```

[1] install `cephadm`, install `podman`, pull `ceph image`, add node to the `orchestrator`, etc..

**Comment by smithfarm** [comment]
+1 for adding `cephadm` role (meaning: "this is a node that will be controlled by cephadm/ceph orchestrator")

**Comment by tserong** [comment]
Don't focus too much on the time server thing, that was just an example. The point I was trying to make is that if the salt master needs to be a minion for *any* reason at all, you still probably don't want it to be under cephadm's control.

If it's annoying to add a cephadm role to every other node, we could reverse that logic, and, say, have a role that excludes a node from cephadm's control? Then you'd only need to apply that role to the master node.
