### ISSUE TITLE
Make bootstrap_mon optional

### ISSUE THREAD

**Issue by swiftgist** [ceph/ceph-salt#265]
For considering upgrades where a Ceph cluster already exists, I think it makes sense to use `ceph-salt apply` for the subset of states that are not related to a fresh deployment.  These are 

```
    - .sshkey
    - .software
    - .container
    - .apparmor
    - .time-prep
    - .time-sync
    - .cephtools
```

If the remaining steps are dependent on the presense of a bootstrap_mon, then

```
    - .cephbootstrap
    - .find-admin-host
    - .cephorch
    - .ceph-admin
```
would run for a fresh deployment.  All other scenarios would skip these parts.

Note that `cephtools` above does have a bootstrap_mon condition for setting the permissions on `/var/log/ceph` that would need to be addressed.

**Comment by tserong** [comment]
We still need the "configure ssh orchestrator" part of cephbootstrap for the upgrade case (see #267)

**Comment by ricardoasmarques** [comment]
Checking for `bootstrap_minion` presence to control if those steps are executed or not will force us to always have a `bootstrap_minion` in our config, even after the initial deployment, otherwise new minions will not be automatically added to the orchestrator.

If we want to keep the behavior of allowing the user to remove the bootstrap minion after day 1, then we need a new setting on `ceph-salt config` to control if those steps should be executed or not.

Not sure what is the best approach here.
